#!/usr/bin/env php
<?php
error_reporting(E_ERROR);
// app/console

require 'vendor/autoload.php';
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new \Ampersand\Console\BuildCommand);
$application->add(new \Ampersand\Console\DeployCommand);
$application->add(new \Ampersand\Console\TokenCommand);
$application->run();
