# URL: http://testftp.endofline.ws
testftp:
    -
        driver: local
        path: 'build/'

    -
        driver: 'ftp'
        host: 'endofline.ws'
        username: 'web53f1'
        password: 'bjwcWkPr'
        root: '/'
        port: 21
        passive: true
        timeout: 20